server:
  port: 8082

spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      routes:
        - id: QUIZ-SERVICE
          uri: lb://QUIZ-SERVICE
          predicates:
            - Path=/api/quiz/**

eureka:
  client:
    serverUrl:
      defaultZone: http://localhost:8761/eureka/
    instance:
      prefer-ip-address: true